I'm sorry, but an uncaught exception occurred.

While running game code:
IOError: [Errno 2] No such file or directory: '/home/sr_benicio/Documentos/Programa/RenNV/Trigger World/game/saves/persistent.1657076738.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/sr_benicio/Público/Renpy/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/home/sr_benicio/Público/Renpy/renpy/main.py", line 665, in main
    renpy.persistent.update(True)
  File "/home/sr_benicio/Público/Renpy/renpy/persistent.py", line 395, in update
    save()
  File "/home/sr_benicio/Público/Renpy/renpy/persistent.py", line 411, in save
    renpy.loadsave.location.save_persistent(data)
  File "/home/sr_benicio/Público/Renpy/renpy/savelocation.py", line 496, in save_persistent
    l.save_persistent(data)
  File "/home/sr_benicio/Público/Renpy/renpy/savelocation.py", line 347, in save_persistent
    with open(fn_tmp, "wb") as f:
IOError: [Errno 2] No such file or directory: '/home/sr_benicio/Documentos/Programa/RenNV/Trigger World/game/saves/persistent.1657076738.tmp'

Linux-5.15.0-40-generic-x86_64-with-debian-bookworm-sid
Ren'Py 7.4.11.2266
Trigger World 1.0
Wed Jul  6 01:09:04 2022
